<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCssRsZy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCssRsZy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCssRsZy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCssRsZy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCssRsZy\App_KernelDevDebugContainer([
    'container.build_hash' => 'CssRsZy',
    'container.build_id' => '2c2d4147',
    'container.build_time' => 1698952452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCssRsZy');
