<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJEUhDxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJEUhDxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJEUhDxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJEUhDxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJEUhDxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'JEUhDxx',
    'container.build_id' => 'bf4d12b5',
    'container.build_time' => 1698870494,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJEUhDxx');
