<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCC6dL4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCC6dL4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZCC6dL4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZCC6dL4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZCC6dL4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZCC6dL4',
    'container.build_id' => 'f8ea0135',
    'container.build_time' => 1698869676,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCC6dL4');
